remove mypy

diff --git a/.github/workflows/jax_setup.yml b/.github/workflows/jax_setup.yml
--- a/.github/workflows/jax_setup.yml
+++ b/.github/workflows/jax_setup.yml
@@ -115,13 +115,13 @@ jobs:
       shell: bash -l {0}
       run: source scripts/framework_list.sh
 
-    - name: Mypy
-      if: ${{ (success() || failure()) && (steps.install.outcome == 'failure' || steps.install.outcome == 'success') }}
-      shell: bash -l {0}
-      run: |
-      for file in "$JAX_FILES"; do
-        mypy -m "$file"
-      done
+    # - name: Mypy
+    #   if: ${{ (success() || failure()) && (steps.install.outcome == 'failure' || steps.install.outcome == 'success') }}
+    #   shell: bash -l {0}
+    #   run: |
+    #   for file in "$JAX_FILES"; do
+    #     mypy -m "$file"
+    #   done
       
     - name: Doctest Linux
       if: ${{ (runner.os == 'Linux') && always() }}
diff --git a/.github/workflows/torch_setup.yml b/.github/workflows/torch_setup.yml
--- a/.github/workflows/torch_setup.yml
+++ b/.github/workflows/torch_setup.yml
@@ -122,13 +122,13 @@ jobs:
       shell: bash -l {0}
       run: source scripts/framework_list.sh
 
-    - name: Mypy
-      if: ${{ (success() || failure()) && (steps.install.outcome == 'failure' || steps.install.outcome == 'success') }}
-      shell: bash -l {0}
-      run: |
-      for file in "$PYTORCH_FILES"; do
-        mypy -m "$file"
-      done
+    # - name: Mypy
+    #   if: ${{ (success() || failure()) && (steps.install.outcome == 'failure' || steps.install.outcome == 'success') }}
+    #   shell: bash -l {0}
+    #   run: |
+    #   for file in "$PYTORCH_FILES"; do
+    #     mypy -m "$file"
+    #   done
       
     - name: PyTest
       if: ${{ (success() || failure()) && (steps.install.outcome == 'failure' || steps.install.outcome == 'success') }}
