refactor to remove giant env.yml

diff --git a/.github/workflows/new_formatting.yml b/.github/workflows/new_formatting.yml
--- a/.github/workflows/new_formatting.yml
+++ b/.github/workflows/new_formatting.yml
@@ -41,28 +41,31 @@ jobs:
       with:
         python-version: '3.9'
 
-    - name: Create env.yml
-      shell: bash
-      run: |
-        python -m pip install --upgrade pip;
-        pip install conda-merge;
-        cd requirements
-        conda-merge env_common.yml env_test.yml env_ubuntu.yml tensorflow/env_tensorflow.cpu.yml torch/env_torch.cpu.yml jax/env_jax.cpu.yml > env.yml
-        cd ..
-        cp requirements/env.yml env.yml
+    # - name: Create env.yml
+    #   shell: bash
+    #   run: |
+    #     python -m pip install --upgrade pip;
+    #     pip install conda-merge;
+    #     cd requirements
+    #     conda-merge env_common.yml env_test.yml env_ubuntu.yml tensorflow/env_tensorflow.cpu.yml torch/env_torch.cpu.yml jax/env_jax.cpu.yml > env.yml
+    #     cd ..
+    #     cp requirements/env.yml env.yml
 
-    - name: Install all dependencies using micromamba
-      uses: mamba-org/provision-with-micromamba@main
-      with:
-        environment-file: env.yml
-        environment-name: deepchem
-        channels: conda-forge,defaults
-        extra-specs: python=${{ matrix.python-version }}
+    # - name: Install all dependencies using micromamba
+    #   uses: mamba-org/provision-with-micromamba@main
+    #   with:
+    #     environment-file: env.yml
+    #     environment-name: deepchem
+    #     channels: conda-forge,defaults
+    #     extra-specs: python=${{ matrix.python-version }}
 
-    - name: Install DeepChem
-      id: install
-      shell: bash -l {0}
-      run: pip install -e .
+    # - name: Install DeepChem
+    #   id: install
+    #   shell: bash -l {0}
+    #   run: pip install -e .
+
+    - name: Install yapf and flake8
+      run: pip install yapf==0.32.0 flake8
 
     - name: Show files modified
       run: |
@@ -83,8 +86,8 @@ jobs:
       shell: bash -l {0}
       run: source scripts/flake8_for_ci.sh
 
-    - name: Mypy
-      if: ${{ (success() || failure()) && (steps.install.outcome == 'failure' || steps.install.outcome == 'success') }}
-      shell: bash -l {0}
-      run: |
-        mypy -p deepchem
+    # - name: Mypy
+    #   if: ${{ (success() || failure()) && (steps.install.outcome == 'failure' || steps.install.outcome == 'success') }}
+    #   shell: bash -l {0}
+    #   run: |
+    #     mypy -p deepchem
